exercises = sorted([
    'Pull ups',
    'Squats',
    'Dips',
    'Lunges',
    'Deadlifts',
    'Push ups',
    'Bench press',
    'Biceps curls',
    'Triceps extensions',
    'Roman deadlift',
    'Front squats',
    'Military press',
    'Running',
    'Calf raises',
    'Sit ups',
    'Plank',
    'Muscle ups',
    'Front lever',
    'OAPs',
    'Swimming',
    'Rope skipping',
    'Rows',
    'Ring muscle ups',
    'Back lever',
    'Planche',
    'Leg press',
    'Nordic curls',
    'HSPUs',
    'Ring dips',
    'Isometric holds',

])
